CREATE SEQUENCE TOUR_CODE_SEQ
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9999999999
    START WITH 1
    NO CYCLE
;

-- CREATE TABLE TOURINFO (
--     TOUR_CODE       CHAR(10)         NOT NULL,
--     PLANNED_DAY     DATE            NOT NULL,
--     PLAN_NO         CHAR(4)         NOT NULL,
--     TOUR_NAME       VARCHAR(300)   NOT NULL,
--     TOUR_DAYS       NUMERIC(2,0)     NOT NULL,
--     DEP_DAY         DATE            NOT NULL,
--     AVA_REC_MAX     NUMERIC(10,0)     NOT NULL,
--     DEP_CODE        CHAR(2)         NOT NULL,
--     ARR_CODE        CHAR(2)         NOT NULL,
--     ACCOM_CODE      CHAR(4)         NOT NULL,
--     BASE_PRICE      NUMERIC(7,0)     NOT NULL,
--     CONDUCTOR       CHAR(1)         DEFAULT '0' NOT NULL,
--     TOUR_ABS        VARCHAR(4000)  NULL,
--     CONSTRAINT TOUR_PK1 PRIMARY KEY(TOUR_CODE),
--        FOREIGN KEY (DEP_CODE) REFERENCES DEPARTURE,
--        FOREIGN KEY (ARR_CODE) REFERENCES ARRIVAL,
--        FOREIGN KEY (ACCOM_CODE) REFERENCES ACCOMMODATION
-- );

INSERT INTO TOURINFO VALUES (nextval('TOUR_CODE_SEQ'), CURRENT_DATE, '0001', 'ツアー名0001', 1, CURRENT_DATE + 5, 1000, '01', '01', '0001', 15000, '1', 'メモ');

COMMIT;

DROP SEQUENCE TOUR_CODE_SEQ;